name: face_app
description: A dating app made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1
  cloud_functions: ^0.4.1+6
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.3+1
  firebase_ml_vision: ^0.9.3+5
  firebase_messaging: ^6.0.9
  google_sign_in: ^4.1.1
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  circular_reveal_animation: ^1.1.5
  intl: ^0.16.0
  permission_handler: ^4.1.0
  image_picker: ^0.6.3
  rxdart: ^0.23.1
  path_provider: ^1.5.1
  http: ^0.12.0+4
  image: 2.1.4
  connectivity: ^0.4.6+2
  flutter_sticky_header: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/logo.png