name: face_app
description: A dating app made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1
  cloud_functions: ^0.4.1+6
  firebase_storage: ^3.1.0
  firebase_auth: ^0.15.2
  firebase_ml_vision: ^0.9.3+5
  google_sign_in: ^4.1.0
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  gradient_widgets: ^0.5.1
  circular_reveal_animation: ^1.1.3
  intl: ^0.16.0
  permission_handler: ^4.0.0
  image_picker: ^0.6.2+3
  rxdart: ^0.22.0
  path_provider: ^1.5.1
  http: ^0.12.0+2
  image: 2.1.4
  font_awesome_flutter: ^8.5.0
  connectivity: ^0.4.6+1
  shared_preferences: ^0.5.6
  flutter_image: ^3.0.0
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
